import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://gamedaytldr.live/")
    page.get_by_role("button", name="Check out").click()
    page.get_by_role("textbox", name="Email").click()
    page.get_by_role("textbox", name="Email").fill("jcschill12@gmail.com")
    page.get_by_role("textbox", name="Email").press("Tab")
    page.locator("iframe[name=\"card-fields-number-kkbywihp4q000000\"]").content_frame.get_by_role("textbox", name="Card number").fill("1")
    page.locator("iframe[name=\"card-fields-number-kkbywihp4q000000\"]").content_frame.get_by_role("textbox", name="Card number").press("Tab")
    page.locator("iframe[name=\"card-fields-expiry-m3xllra939d00000\"]").content_frame.get_by_role("textbox", name="Expiration date (MM / YY)").fill("03 / 30")
    page.locator("iframe[name=\"card-fields-expiry-m3xllra939d00000\"]").content_frame.get_by_role("textbox", name="Expiration date (MM / YY)").press("Tab")
    page.locator("iframe[name=\"card-fields-verification_value-b6havdotplk00000\"]").content_frame.get_by_role("textbox", name="Security code").fill("111")
    page.locator("iframe[name=\"card-fields-verification_value-b6havdotplk00000\"]").content_frame.get_by_role("textbox", name="Security code").press("Tab")
    page.get_by_role("button", name="More information about").press("Tab")
    page.locator("iframe[name=\"card-fields-name-4h06ew0zdjq00000\"]").content_frame.get_by_role("textbox", name="Name on card").fill("1")
    page.get_by_role("textbox", name="First name").click()
    page.get_by_role("textbox", name="First name").press("CapsLock")
    page.get_by_role("textbox", name="First name").fill("J")
    page.get_by_role("textbox", name="First name").press("CapsLock")
    page.get_by_role("textbox", name="First name").fill("Jordan")
    page.get_by_role("textbox", name="First name").press("Tab")
    page.get_by_role("textbox", name="Last name").press("CapsLock")
    page.get_by_role("textbox", name="Last name").fill("S")
    page.get_by_role("textbox", name="Last name").press("CapsLock")
    page.get_by_role("textbox", name="Last name").fill("Schilling")
    page.get_by_role("textbox", name="Last name").press("Tab")
    page.get_by_role("combobox", name="Address").fill("111")
    page.get_by_role("option", name="111 North Orange Avenue,").click()
    page.get_by_role("button", name="Pay now").click()
    page.get_by_role("link", name="Continue shopping").click()